### ISSUE TITLE
Priv to bypass noclip hurt

### ISSUE THREAD

**Issue by Andarius68** [mt-mods/beowulf#18]
I have an enhancement request. Some of my trusted players and myself use a mod from the szutils pack called szutil watch to watch new players and others to check for suspicious activity or shady behavior. This mod comes with the watch privledge. However, with beowulf noclip hurt enabled players in this spectator mode also take damage while watching other players due to noclip. It would be nice to be able to set a priv to give certain trusted players a bypass on the noclip hurt in circumstances like this. Thank you. :)

**Comment by S-S-X** [comment]
Don't think this can or should be handled here. I guess also any other node that causes damage would hurt and kill them.

I'd say spectator mods should allow making player immortal preferably ignoring all environment effects that can be ignored. That's because while in spectator mode players are not supposed to really be there but it is more about simulating free camera control.

**Comment by Andarius68** [comment]
Fair enough. That makes sense.
